'use client';

import { useState } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { X, FileText, Ban, AlertOctagon, Fingerprint, MapPin } from 'lucide-react';
import { Suspect } from '@/lib/api';

interface ForensicModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSuspend: (id: string) => Promise<void>;
    data: {
        name: string;
        id: string;
        department: string;
        riskScore: number;
        anomalies: string[];
    } | null;
}

export default function ForensicReportModal({ isOpen, onClose, onSuspend, data }: ForensicModalProps) {
    const [isSuspending, setIsSuspending] = useState(false);

    if (!isOpen || !data) return null;

    const handleSuspend = async () => {
        setIsSuspending(true);
        // Simulator: "Connecting to IFMIS..."
        await new Promise(resolve => setTimeout(resolve, 2000));
        await onSuspend(data.id);
        setIsSuspending(false);
        onClose();
    };

    const generatePDF = () => {
        const doc = new jsPDF();

        // 1. Header (Coat of Arms simulation & Title)
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text("REPUBLIC OF KENYA", 105, 20, { align: "center" });

        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.text("MINISTRY OF PUBLIC SERVICE", 105, 30, { align: "center" });
        doc.setFont("helvetica", "bold");
        doc.setTextColor(220, 38, 38); // Red color for "FRAUD DETECTION UNIT"
        doc.text("FRAUD DETECTION UNIT", 105, 36, { align: "center" });
        doc.setTextColor(0, 0, 0); // Reset to black

        // Separator Line
        doc.setLineWidth(0.5);
        doc.line(20, 42, 190, 42);

        // 2. Suspect Details Box
        doc.setFontSize(10);
        doc.setFont("courier", "normal"); // Monospace for technical/dossier feel

        const startY = 55;
        const lineHeight = 7;

        doc.text(`STOP ORDER REFERENCE: #SUSP-${Math.floor(Math.random() * 100000)}`, 20, startY);
        doc.text(`SUSPECT NAME:       ${data.name.toUpperCase()}`, 20, startY + lineHeight);
        doc.text(`EMPLOYEE ID:        ${data.id}`, 20, startY + lineHeight * 2);
        doc.text(`DEPARTMENT:         ${data.department.toUpperCase()}`, 20, startY + lineHeight * 3);

        // Risk Score Highlight
        doc.setTextColor(220, 38, 38);
        doc.text(`CALCULATED RISK:    ${data.riskScore}%`, 20, startY + lineHeight * 4);
        doc.setTextColor(0, 0, 0);

        // 3. Evidence Table
        // Prepare table data
        const tableData = data.anomalies.map((anomaly, index) => [index + 1, anomaly, "CRITICAL"]);

        autoTable(doc, {
            startY: 100,
            head: [['#', 'ANOMALY DETECTED', 'SEVERITY']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255] },
            styles: { font: 'courier', fontSize: 10 },
            columnStyles: {
                0: { cellWidth: 15 },
                1: { cellWidth: 'auto' },
                2: { cellWidth: 40, textColor: [220, 38, 38], fontStyle: 'bold' }
            }
        });

        // 4. Footer / Authorization
        const finalY = (doc as any).lastAutoTable.finalY + 30;

        doc.setFont("helvetica", "italic");
        doc.setFontSize(8);
        doc.text("This document is system-generated by HAKIKI AI Sovereign System.", 105, 280, { align: "center" });
        doc.text(`Timestamp: ${new Date().toLocaleString()}`, 105, 285, { align: "center" });

        doc.save(`Forensic_Report_${data.id}.pdf`);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center font-sans p-4">
            {/* Backdrop */}
            <div
                className="absolute inset-0 bg-black/80 backdrop-blur-sm transition-opacity"
                onClick={onClose}
            />

            {/* Modal Card */}
            <div className="relative w-full max-w-2xl bg-slate-900 border border-slate-700 shadow-2xl rounded-xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">

                {/* Header */}
                <div className="bg-slate-950 p-6 border-b border-slate-800 flex justify-between items-start relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-1 h-full bg-red-600"></div>
                    <div>
                        <h2 className="text-2xl font-bold text-slate-100 flex items-center gap-3">
                            {data.name}
                            <span className="text-sm font-mono font-normal text-slate-400 bg-slate-800 px-2 py-0.5 rounded border border-slate-700">
                                {data.id}
                            </span>
                        </h2>
                        <div className="text-red-500 font-mono text-xs uppercase mt-1 tracking-wider flex items-center gap-1">
                            <AlertOctagon className="w-3 h-3" />
                            High Priority Target • {data.department} Dept
                        </div>
                    </div>
                    <button
                        onClick={onClose}
                        className="text-slate-500 hover:text-white transition-colors p-1 hover:bg-slate-800 rounded-lg"
                    >
                        <X className="w-6 h-6" />
                    </button>
                </div>

                {/* Body */}
                <div className="p-8 space-y-6">

                    {/* Risk Badge */}
                    <div className="flex items-center justify-between bg-red-950/20 border border-red-900/30 p-4 rounded-lg">
                        <div className="text-red-400 text-sm font-medium uppercase tracking-wide">
                            Calculated Risk Score
                        </div>
                        <div className={`text-4xl font-black font-mono tracking-tighter ${data.riskScore > 80 ? 'text-red-500' : 'text-orange-500'}`}>
                            {data.riskScore}%
                        </div>
                    </div>

                    {/* Evidence Section */}
                    <div>
                        <h3 className="text-slate-400 text-xs uppercase font-bold tracking-widest mb-4 border-b border-slate-800 pb-2">
                            Forensic Evidence
                        </h3>

                        <div className="space-y-4">
                            {data.anomalies.map((anomaly, index) => (
                                <div key={index} className="flex gap-4 items-start">
                                    <div className="p-2 bg-slate-800 rounded text-red-400 mt-1">
                                        <Fingerprint className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <h4 className="text-slate-200 font-semibold text-sm uppercase">Anomaly Detected</h4>
                                        <p className="text-red-400 font-mono text-sm mt-1 border-l-2 border-red-500/50 pl-3">
                                            {anomaly}
                                        </p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                </div>

                {/* Footer */}
                <div className="bg-slate-950 p-6 border-t border-slate-800 flex items-center justify-between gap-4">
                    <button
                        onClick={generatePDF}
                        className="flex-1 py-3 px-4 border border-slate-700 rounded-lg text-slate-300 font-medium hover:bg-slate-800 hover:text-white transition-all flex items-center justify-center gap-2 text-sm"
                    >
                        <FileText className="w-4 h-4" />
                        📄 EXPORT DOSSIER
                    </button>

                    <button
                        onClick={handleSuspend}
                        disabled={isSuspending}
                        className="flex-[1.5] py-3 px-4 bg-red-600 hover:bg-red-500 text-white rounded-lg font-bold uppercase tracking-wide shadow-[0_0_20px_rgba(220,38,38,0.4)] hover:shadow-[0_0_30px_rgba(220,38,38,0.6)] transition-all flex items-center justify-center gap-2 text-sm animate-pulse-slow active:scale-95 group disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {isSuspending ? (
                            <>
                                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                Connecting...
                            </>
                        ) : (
                            <>
                                <Ban className="w-4 h-4 group-hover:rotate-90 transition-transform" />
                                Generate Stop Order
                            </>
                        )}
                    </button>
                </div>

            </div>
        </div>
    );
}
